{
 "title": "Theia Cloud",
 "description": "Visualization to observe a Theia Cloud deployment",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Theia Cloud", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Theia Session Pod Count",
   "type": "timeseries",
   "description": "Shows the number of running session pods.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count(up{job=\"theia-prometheus-stack/theiacloud-sessions\"})",
     "legendFormat": "Theia Session Count"
    }
   ]
  },
  {
   "title": "Theia Cloud CPU usage",
   "type": "timeseries",
   "description": "CPU usage of all Theia Cloud pods. This includes session pods and service pods (i.e. landing page, REST service, operator).\nAlso shows the total over all Theia Cloud pods.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"theia-prod\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container!=\"POD\",container!=\"\", job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"theia-prod\"}[1m]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "Theia Session Backend Memory",
   "type": "timeseries",
   "description": "Theia Backend process memory consumption for each session pod",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=\"theia-prod\", job=\"theia-prometheus-stack/theiacloud-sessions\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Theia Session Backend CPU",
   "type": "timeseries",
   "description": "CPU usage for Theia Backend processes for each session pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=\"theia-prod\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Nodes CPU Usage Ratio",
   "type": "timeseries",
   "description": "CPU Usage ratio per node in the cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "instance:node_cpu:ratio", "legendFormat": "Node {{instance}}" }
   ]
  },
  {
   "title": "Nodes Memory Usage Ratio",
   "type": "timeseries",
   "description": "Memory Usage Ratio for each node in the cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Cluster CPU Usage Ratio",
   "type": "timeseries",
   "description": "Ratio of CPUs used across the whole cluster",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "cluster:node_cpu:ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cluster Memory Usage Ratio",
   "type": "timeseries",
   "description": "Memory usage across the whole cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}