---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: landing-page-cert
  namespace: theia-prod
spec:
  secretName: landing-page-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: theia.artemis.cit.tum.de
  dnsNames:
    - theia.artemis.cit.tum.de
  privateKey:
    rotationPolicy: Never
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: service-cert
  namespace: theia-prod
spec:
  secretName: service-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: service.theia.artemis.cit.tum.de
  dnsNames:
    - service.theia.artemis.cit.tum.de
  privateKey:
    rotationPolicy: Never
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: instance-cert
  namespace: theia-prod
spec:
  secretName: ws-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: instance.theia.artemis.cit.tum.de
  dnsNames:
    - instance.theia.artemis.cit.tum.de
  privateKey:
    rotationPolicy: Never
