{
 "title": "Theia Cloud Session Startup Time",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(application_application_theiacloud_session_startup_seconds_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Average Session Startup Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(application_application_theiacloud_session_startup_seconds_seconds_sum{namespace=\"$namespace\"}[5m]) \n/ \nrate(application_application_theiacloud_session_startup_seconds_seconds_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{app_definition}}"
    }
   ]
  },
  {
   "title": "Median Session Startup Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "application_application_theiacloud_session_startup_seconds_seconds{namespace=\"$namespace\", quantile=\"0.5\"}",
     "legendFormat": "{{app_definition}}"
    }
   ]
  },
  {
   "title": "P95 Session Startup Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "application_application_theiacloud_session_startup_seconds_seconds{namespace=\"$namespace\", quantile=\"0.95\"}",
     "legendFormat": "{{app_definition}}"
    }
   ]
  },
  {
   "title": "P99 Session Startup Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "application_application_theiacloud_session_startup_seconds_seconds{namespace=\"$namespace\", quantile=\"0.99\"}",
     "legendFormat": "{{app_definition}}"
    }
   ]
  }
 ]
}